(function() {
  // tFrame is a DOMHighResTimeStamp, accurate to 1/1000 of a ms
  function main(tFrame) {
    window.requestAnimationFrame(main);

    // stopMain contains the token ID generated by requestAnimationFrame
    MyGame.stopMain = window.requestAnimationFrame(main);
    var nextTick = MyGame.lastTick + MyGame.tickLength;
    var numTicks = 0;

    if (tFrame > nextTick) {
      var timeSinceTick = tFrame - MyGame.lastTick;
      numTicks = Math.floor(timeSinceTick / MyGame.tickLength);
    }

    queueUpdates(numTicks);
    render(tFrame);
    MyGame.lastRender = tFrame;
    // var tNow = window.performance.now(); // Get timestamp which is the number of ms since navigationStart
    // console.log(tNow);

    // This cancels the request that corresponds to the token
    // window.cancelAnimationFrame( MyGame.stopMain );

    // console.log(stopMain);
  }

  function queueUpdates(numTicks) {
    for (var i = 0; i < numTicks; i++) {
      MyGame.lastTick = MyGame.lastTick + MyGame.tickLength;
      update(MyGame.lastTick);
    }
  }

  var MyGame = {
    stopMain: 0,
    lastTick: performance.now(),
    lastRender: MyGame.lastTick,
    tickLength: 50
  };

  main(performance.now()); // Start the cycle
})();
